routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\Admin\AdminHomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\VariantController;
use App\Http\Controllers\BlogPostController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PageController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\CountryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route patterns */

Route::pattern('slug', '[a-z0-9\-]+');

/* Admin Routes */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::group(['middleware' => ['auth', 'admin_access']], function () {

        Route::get('/{index?}', [AdminHomeController::class, 'index'])->name('home')->where('index', 'home');

        Route::get('user', [UserController::class, 'editSelf'])->name('user');

        Route::view('/style', 'admin.style');

        foreach (File::allFiles(__DIR__ . '/admin') as $partial) {
            require_once $partial->getPathname();
        }
    });
});

Auth::routes();

Route::post('login', [LoginController::class, 'login']);
Route::get('logout', [LoginController::class, 'logout']);

/* Frontend Routes */
Route::get('/{index?}', [HomeController::class, 'show'])->name('home')->where('index', 'home');

Route::post('enquiry', [ContactController::class, 'sendEnquiry'])->name('enquiry');

Route::group(['prefix' => 'blog', 'as' => 'blog'], function () {
    Route::get('/', [BlogPostController::class, 'index'])->name('index');
    Route::get('{slug}', [BlogPostController::class, 'show'])->name('show');
});

Route::group(['prefix' => 'shop', 'as' => 'products.'], function () {
    Route::group(['prefix' => 'categories', 'as' => 'products.categories.'], function () {
        Route::get('/', [ProductController::class, 'categories'])->name('index');
        Route::get('/{slug}', [ProductController::class, 'category'])->name('show');
    });
    Route::get('/', [ProductController::class, 'index'])->name('index');
    Route::get('/{slug}', [ProductController::class, 'show'])->name('show');
});

Route::get('variant/{id}', [VariantController::class, 'show']);

Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::group(['middleware' => 'order_exists'], function () {
        Route::get('/', [OrderController::class, 'getCart'])->name('show');
        Route::post('/', [OrderController::class, 'updateCart'])->name('update');
    });

    Route::group(['middleware' => 'cart_details'], function () {
        Route::post('add', [OrderController::class, 'addItem'])->name('add');
        Route::post('remove', [OrderController::class, 'removeItem'])->name('remove');
    });
});

Route::group(['prefix' => 'account', 'as' => 'account.', 'middleware' => 'auth'], function () {
    Route::get('/', function () {
        return redirect()->to('/account/details');
    });

    Route::get('details', [AccountController::class, 'getDetails'])->name('details');
    Route::post('details', [AccountController::class, 'postDetails'])->name('details');

    Route::get('orders', [AccountController::class, 'getOrders'])->name('orders.index');
    Route::get('order/{token}', [AccountController::class, 'showOrder'])->name('order.show');

    Route::get('addresses', [AccountController::class, 'getAddresses'])->name('addresses');
    Route::post('addresses', [AccountController::class, 'postAddresses'])->name('addresses');

    Route::get('password', [AccountController::class, 'getPassword'])->name('password');
    Route::post('password', [AccountController::class, 'postPassword'])->name('password');
});

Route::group(['prefix' => 'checkout', 'as' => 'checkout.', 'middleware' => 'order_exists'], function () {

    Route::get('/', [CheckoutController::class, 'checkout']);
    Route::post('email', [CheckoutController::class, 'postEmail'])->name('email');

    Route::post('coupon', [CheckoutController::class, 'applyCoupon'])->name('coupon');

    Route::get('addresses', [CheckoutController::class, 'getAddresses'])->name('addresses');
    Route::post('addresses', [CheckoutController::class, 'postAddresses'])->name('addresses');

    Route::get('shipping', [CheckoutController::class, 'getShipping'])->name('shipping');
    Route::post('shipping', [CheckoutController::class, 'postShipping'])->name('shipping');

    Route::get('payment', [CheckoutController::class, 'getPayment'])->name('payment');
    Route::post('payment', [CheckoutController::class, 'postPayment'])->name('payment');

    Route::get('confirm', [CheckoutController::class, 'confirmPayment'])->name('confirm');
});

Route::get('checkout/cancelled', [CheckoutController::class, 'paymentCancelled'])->name('checkout.cancelled');

Route::group(['prefix' => 'countries', 'as' => 'countries.'], function () {
    Route::get('/', [CountryController::class, 'getCountries']);
    Route::get('/{name}/states', [CountryController::class, 'getStates']);
});

Route::get('order/{token}/complete', [OrderController::class, 'complete'])->name('order.complete');

Route::get('{slug}', [PageController::class, 'show'])->name('pages.show');

app/Models/Notification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    protected $table = 'notifications';

    protected $fillable = ['notification', 'display_from', 'display_to'];

    public $dates = ['display_from', 'display_to'];

    public function getExtractAttribute()
    {
        if (strlen(strip_tags($this->notification)) > 200)
            return substr(strip_tags($this->notification), 0, 200) . "...";

        return strip_tags($this->notification);
    }
}

app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Notification;
use Illuminate\Http\Request;
use Validator;

class NotificationController extends Controller
{
    /**
     * Index of notifications
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notifications = Notification::paginate(50);

        return view('admin.notifications.index', compact('notifications'));
    }

    /**
     * Create a new notification
     *
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function create(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'notification' => 'required'
        ], [
            'notification.required' => 'Please enter the text of the notification you are creating'
        ]);

        if ($validator->fails())
            return redirect()->back()->withErrors($validator)->withInput();

        $notification = Notification::create(['notification' => $request->notification]);

        return redirect()->to('/admin/notifications/' . $notification->id . '/edit')->with('success', 'You have successfully created this notification!');
    }

    /**
     * Edit notification
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $notification = Notification::where('id', $id)->first();

        return view('admin.notifications.edit', compact('notification'));
    }

    /**
     * Update existing notification
     *
     * @param Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'notification' => 'required'
        ], [
            'notification.required' => 'Please enter the text of the notification you are creating'
        ]);

        if ($validator->fails())
            return redirect()->back()->withErrors($validator)->withInput();

        $notification = Notification::where('id', $id)->first();
        $notification->update([
            'notification' => $request->notification,
            'display_from' => $request->display_from,
            'display_to' => $request->display_to
        ]);

        return redirect()->to('/admin/notifications')->with('success', 'You have successfully updated this notification!');
    }

    /**
     * Delete notification
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete($id)
    {
        Notification::where('id', $id)->delete();

        return redirect()->back()->with('success', 'You have successfully deleted this notification!');
    }
}

resources/views/admin/notifications/edit.blade.php
@extends("admin.layouts.master")

@section('content')
{!! Form::open(['route' => ['admin.notifications.update', $notification->id], 'method' => 'POST',  'enctype' => 'multipart/form-data']) !!}
    <div class="section-head">
        <div class="content">
            <h2 class="mb-2">Edit notification</h2>
        </div>
        {!! Form::submit('Save notification', ['class' => 'button blue flex-shrink-0']) !!}
    </div>

    <div class="card-group mb-5">
        <div class="card-col w-full">
            <div class="card">
                <div class="flex flex-wrap">
                    <div class="flex flex-wrap w-full">
                        <fieldset class="mb-6 px-1 w-full">
                            {!! Form::label('notification', 'Notification', ['class' => 'field-label']) !!}
                            {!! Form::text('notification', $notification->notification, ["class" => "field-input"]) !!}
                            <span class="field-error">{!! $errors->first('notification') !!}
                        </fieldset>
                        <fieldset class="mb-6 px-1 w-1/2">
                            {!! Form::label('display_from', 'Display From', ['class' => 'field-label']) !!}
                            {!! Form::text('display_from', $notification->display_from ? $notification->display_from : null, ['id' => 'display_from', 'class' => 'field-input flatpickr',
                                'data-enable-time' => 'true',
                                'data-date-format' => 'Y-m-d H:i:S',
                                'data-alt-input' => 'true',
                                'data-alt-format' => 'l F J, Y - h:i K'
                            ]) !!}
                            <span class="field-error">{!! $errors->first('display_from') !!}
                        </fieldset>
                        <fieldset class="mb-6 px-1 w-1/2">
                            {!! Form::label('display_to', 'Display To', ['class' => 'field-label']) !!}
                            {!! Form::text('display_to', $notification->display_to ? $notification->display_to : null, ['id' => 'display_to', 'class' => 'field-input flatpickr',
                                'data-enable-time' => 'true',
                                'data-date-format' => 'Y-m-d H:i:S',
                                'data-alt-input' => 'true',
                                'data-alt-format' => 'l F J, Y - h:i K'
                            ]) !!}
                            <span class="field-error">{!! $errors->first('display_to') !!}
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
{!! Form::close() !!}
@stop

@section('templates')
@stop

@section('scripts')
@stop

resources/views/admin/notifications/index.blade.php
@extends("admin.layouts.master")

@section('content')
<div class="section-head">
    <div class="content">
        <h2 class="mb-2">Notifications</h2>
    </div>
    {!! Form::button('New notification', ['id' => 'create-record', 'data-target' => 'create-record-form', 'class' => 'button button green flex-shrink-0 create-record']) !!}
</div>

<div class="card-group">
    <div class="card-col w-full">
        <div class="card">
            @if (count($notifications) > 0)
                <ul class="list-hierarchy">
                    @foreach($notifications as $notification)
                        <li data-id="{{$notification->id}}">
                            <span>
                                <a href="{!! url('admin/notifications/'.$notification->id.'/edit') !!}" title="Edit insight">{!! $notification->extract !!}</a>
                                <span class="buttons">
                                    <a href="{!! url('admin/notifications/'.$notification->id.'/edit') !!}" class="text-green-500 mr-2" title="Edit notification"><i class="fa fa-edit"></i></a>
                                    <a href="{!! url('admin/notifications/'.$notification->id.'/delete') !!}" class="text-red-500 delete-confirm" title="Delete notification"><i class="fa fa-trash"></i></a>
                                </span>
                            </span>
                        </li>
                    @endforeach
                </ul>

                {!! $notifications->links() !!}
            @else
                <span class="list-empty">There are no notifications to display.</span>
            @endif
        </div>
    </div>
</div>
@stop

@section('templates')
<div id="overlay"></div>
{!! Form::open(['route' => 'admin.notifications.create', 'id' => 'create-record-form', 'class' => 'card modal max-w-2xl' . (count($errors) ? ' errors' : '')]) !!}
    <header class="mb-4 px-1">
        <h3>Create a new notification</h3>
    </header>
    <div>
        <fieldset class="mb-6 px-1">
            {!! Form::label('notification', 'Notification', ['class' => 'field-label']) !!}
            {!! Form::text('notification', null, ['id' => 'notification', 'class' => 'field-input', 'placeholder' => 'Enter your notification text here...', 'data-validation' => 'req']) !!}
            <span class="field-error">{!! $errors->first('notification') !!}</span>
        </fieldset>
        <fieldset class="px-1">
            {!! Form::button('Create', ['type' => 'submit', 'class' => 'button green']) !!}
            <a id="cancel-create-record" class="button red thin" role='cancel-create-record'>Cancel</a>
        </fieldset>
    </div>
{!! Form::close() !!}
@stop

@section('scripts')
@stop